// Logs in as admin and posts the CSVs generated by generate-historical-data.ts
// through the real /api/migration endpoint, in dependency order (vendors before
// purchase-orders). Populates circulation/vendor/PO/serials/gate-visit history so
// Reports, Dashboard, and Gate footfall charts have real multi-month data.
//
// Prereqs: `npx tsx scripts/generate-historical-data.ts` has been run, and the app is up.
// Usage: BASE_URL=http://localhost:3000 npx tsx scripts/import-historical-data.ts

import fs from "fs";
import path from "path";

const BASE_URL = process.env.BASE_URL ?? "http://localhost:3000";
const ADMIN_EMAIL = process.env.ADMIN_EMAIL ?? "admin@amcengineering.edu.in";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? "Admin@123";

const jar = new Map<string, string>();

function storeCookies(res: Response) {
  const setCookies =
    typeof (res.headers as any).getSetCookie === "function"
      ? (res.headers as any).getSetCookie()
      : [res.headers.get("set-cookie")].filter(Boolean) as string[];
  for (const raw of setCookies) {
    const [pair] = raw.split(";");
    const idx = pair.indexOf("=");
    jar.set(pair.slice(0, idx), pair.slice(idx + 1));
  }
}
function cookieHeader(): string {
  return [...jar.entries()].map(([k, v]) => `${k}=${v}`).join("; ");
}

async function login() {
  console.log(`🔐 Logging in as ${ADMIN_EMAIL} ...`);
  const csrfRes = await fetch(`${BASE_URL}/api/auth/csrf`);
  storeCookies(csrfRes);
  const { csrfToken } = (await csrfRes.json()) as { csrfToken: string };

  const loginRes = await fetch(`${BASE_URL}/api/auth/callback/credentials`, {
    method: "POST",
    redirect: "manual",
    headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json", Cookie: cookieHeader() },
    body: new URLSearchParams({ csrfToken, email: ADMIN_EMAIL, password: ADMIN_PASSWORD, callbackUrl: `${BASE_URL}/dashboard`, json: "true" }),
  });
  storeCookies(loginRes);

  const sessionRes = await fetch(`${BASE_URL}/api/auth/session`, { headers: { Cookie: cookieHeader() } });
  storeCookies(sessionRes);
  const session = await sessionRes.json();
  if (!session?.user) throw new Error(`Login failed — status ${loginRes.status}`);
  console.log(`✅ Logged in as ${session.user.email} (role: ${session.user.role})`);
}

async function importFile(filePath: string, type: string) {
  if (!fs.existsSync(filePath)) {
    console.log(`⚠️  Skipping ${type} — ${filePath} not found.`);
    return;
  }
  const buf = fs.readFileSync(filePath);
  const rowCount = buf.toString("utf8").split("\n").filter(Boolean).length - 1;

  const form = new FormData();
  form.append("file", new Blob([buf], { type: "text/csv" }), path.basename(filePath));
  form.append("type", type);

  console.log(`\n📤 Importing ${rowCount} ${type} rows ...`);
  const start = Date.now();
  const res = await fetch(`${BASE_URL}/api/migration`, { method: "POST", headers: { Cookie: cookieHeader() }, body: form });
  const elapsedMs = Date.now() - start;
  const body = await res.json().catch(() => ({}));

  console.log(`   HTTP ${res.status} in ${elapsedMs}ms — imported=${body.imported} failed=${body.failed} total=${body.total}`);
  if (body.failures?.length) console.log(`   Sample failures:`, JSON.stringify(body.failures.slice(0, 3), null, 2));
}

async function main() {
  await login();
  const dir = path.join(process.cwd(), "test-data");

  // Order matters: vendors must exist before purchase-orders references them.
  await importFile(path.join(dir, "vendors.csv"), "vendors");
  await importFile(path.join(dir, "purchase-orders.csv"), "purchase-orders");
  await importFile(path.join(dir, "circulation.csv"), "circulation");
  await importFile(path.join(dir, "serials.csv"), "serials");
  await importFile(path.join(dir, "gate-visits.csv"), "gate-visits");
  await importFile(path.join(dir, "digital-library.csv"), "digital-library");
  await importFile(path.join(dir, "reservations.csv"), "reservations");
}

main().catch((err) => { console.error("❌", err); process.exit(1); });
